apiVersion: v1
kind: Secret
metadata:
  name: slack-secret
type: Opaque
stringData:
  # Add your slack bot token and slack workspace team id
  # Important: not for production use, demo purposes only
  slack-bot-token: "xoxb-"
  slack-team-id: "T-"