---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/name: llama-stack-k8s-operator
    control-plane: controller-manager
    argocd.argoproj.io/instance: llama-stack
  name: llama-stack-k8s-operator-controller-manager
