---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: llama-stack-k8s-operator
    argocd.argoproj.io/instance: llama-stack
  name: llama-stack-k8s-operator-controller-manager
  namespace: llama-stack-k8s-operator-controller-manager
