---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: llama-stack-k8s-operator
    control-plane: controller-manager
    argocd.argoproj.io/instance: llama-stack
  name: llama-stack-k8s-operator-controller-manager-metrics-service
  namespace: llama-stack-k8s-operator-controller-manager
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    app.kubernetes.io/name: llama-stack-k8s-operator
    control-plane: controller-manager
